version: "2.1"

services:
    nginx:
        build: ./nginx/
        container_name: delivery_nginx
        dns_search: nginx
        ports:
            - 8080:80
        volumes:
            - "./code:/var/www/html:ro"
        links:
            - php
            - mysql
        depends_on:
            - composer
    php:
        build: ./php/
        container_name: delivery_php
        expose:
            - 9000
        volumes:
            - "./code:/var/www/html"
        working_dir: /var/www/html
        dns_search: php
        depends_on:
            - mysql

    mysql:
        build: ./mysql/
        container_name: delivery_mysql
        volumes:
            - ./db-data:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        dns_search: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "deliveryorders"
        restart: always


    composer:
        container_name: delivery_composer
        restart: 'no'
        image: composer/composer:php7
        command: install
        working_dir: /var/www/html
        volumes:
            - "./code:/var/www/html"

volumes:
    db-data:
      driver: local

